[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true

[invariant]
runs = 64
depth = 12

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
